### ISSUE TITLE
Requesting changes to 'Update Account' (update-account) Beta API

### ISSUE THREAD

**Issue by jason545454** [sailpoint-oss/developer.sailpoint.com#293]
Firstly, how is the PATCH /beta/accounts/:id different from the PATCH /v3/accounts/:id ?

I tried both (in postman) and they seem to function the same

/beta only allowed the update of the the following fields ONLY  (same as v3):
* identityId
* manuallyCorrelated

**To Reproduce** 
1. Run PATCH /v3/accounts/:id 
2. Run PATCH /beta/accounts/:id 

**Additional context** 
If /beta only allows updating too of those 2 attributes, please update beta page to say so too.

**Ideal Outcome** 
/beta/accounts/:id would allow updating of *all* attributes, not just those 2.

Thank you

**Comment by colin-mckibben-sp** [comment]
Beta and v3 endpoints will usually be the same.  This is because beta endpoints are promoted to v3 once the beta is deemed ready for long term support.  The beta endpoint remains so we don't break any integrations that rely on it.  

As for your request to allow updating more attributes using PATCH, that is feedback we have received here: https://developer.sailpoint.com/discuss/t/post-api-account-setaccountdata/8808/4.

Given that the v3 version is preferred over beta, we won't be making any update to the beta spec.

**Comment by jason545454** [comment]
Thanks @colin-mckibben-sp 

Would it make sense then on the /beta page to make a banner/note that it has been promoted to /v3, and therefore to refer to /v3 page for accurate documentation?
