### ISSUE TITLE
[Bug] 'Create a campaign' (create-campaign) allows duplicate campaigns to be created

### ISSUE THREAD

**Issue by jason545454** [sailpoint-oss/developer.sailpoint.com#384]
**Describe the bug** 

In the UI, you cannot create a campaign with the same name as one that already exists.
This limitation is not enforced using the API. You can create multiple different campaigns with the same name.

**To Reproduce** Steps to reproduce the behavior:

1. In the UI, create a campaign called "test"
2. Create another campaign called "test using the UI - it wont let you save
3. Using the API - POST /v3/campaigns with valid JSON body, create a campaign called "test"
4. Re-submit the same POST request several times
5. You will now see several campaigns called "test"

**Expected behavior** 

I assume campaign names should be unique

**Comment by colin-mckibben-sp** [comment]
Thank you for your bug report. I spoke with our product team and this is the expected behavior. There is no technical issue with campaigns having the same name, hence why the API doesn't perform duplicate name validation. The UI performs the name check to avoid confusion with campaigns that have the same name. You can replicate this validation in the API by using the [list campaigns](https://developer.sailpoint.com/idn/api/v3/get-active-campaigns) endpoint and filtering on `name` and `status` to see if there is a campaign that has the same name as the one you are about to create.
