### ISSUE TITLE
[Bug] Can make API calls, But cannot add Authorization to a number of Endpoint pages

### ISSUE THREAD

**Issue by luke-hagar-sp** [sailpoint-oss/developer.sailpoint.com#62]
**Describe the bug**
I am able to make fetch requests in the UI, and populate a tenant for them, but I cannot supply a JWT for the call

**To Reproduce**
1. Go to the Beta API documentation
2. Go to the Access Profiles section (Affecting a number of endpoints, this is just an example)
3. Click on the edit button for the server
4. Supply the tenant
5. Click "Send Request"
6. See error

**Expected behavior**
This function should allow me to make API calls against my tenant

**Screenshots**

**Operating System (please complete the following information):**
 - Browser: Vivaldi 5.4.2753.51 (Stable channel) (arm64) 
 - OS: MacOS Monterey 12.6
 - CLI Environment NA

**Additional context**
I believe this issue has to do with the lack of a a security section in the Open API spec file for the endpoint between the description and parameters sections
![Screen Shot 2022-09-29 at 9 52 07 AM](https://user-images.githubusercontent.com/98849695/193065316-b09d48d5-8429-4375-8ddc-1cfb91d12bb1.png)
![Screen Shot 2022-09-29 at 9 35 34 AM](https://user-images.githubusercontent.com/98849695/193065327-6bddf68f-d389-4703-94cf-d431a0354fd9.png)
![Screen Shot 2022-09-29 at 9 35 26 AM](https://user-images.githubusercontent.com/98849695/193065330-64365f2b-866a-49a6-b571-038dcc710d2f.png)

**Comment by jordan-violet-sp** [comment]
Confirmed to be the case in the latest build. @philip-ellis-sp is investigating.

**Comment by philip-ellis-sp** [comment]
Turns out in the API spec we are overriding the default authentication in multiple endpoints when adding the scopes to the authentication. This is being done incorrectly and needs to be updated.

For example, in the accounts specification there is a security tag used to define the scope:

```yaml
  security:
    - bearerAuth:
        - idn:account-list:read
```
To properly add the scope to the call, it needs to be added to the base oath2 definition:
```yaml
  security:
    - oauth2: [idn:account-list:read]
```
I will be change the security for the affected APIs in our specification and this problem should be resolved.

**Comment by LukeHagar** [comment]
Woot woot!
